// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm6kkVAZH1BcpFRuk-kdT6_JCWw7NNKYE',
    appId: '1:594925660223:web:968d8d968612b8eb83b08a',
    messagingSenderId: '594925660223',
    projectId: 'chatapp-ccd52',
    authDomain: 'chatapp-ccd52.firebaseapp.com',
    storageBucket: 'chatapp-ccd52.appspot.com',
    measurementId: 'G-F2STH2V9L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNHtnxf-uPLH2OTfox29XEPP-e7SXzUx4',
    appId: '1:594925660223:android:03d5c1d2bfe782fe83b08a',
    messagingSenderId: '594925660223',
    projectId: 'chatapp-ccd52',
    storageBucket: 'chatapp-ccd52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSDb_q7ZIsBXc8tQVDc2x2KgCdhDRS8ws',
    appId: '1:594925660223:ios:d569d9564a9ddfa583b08a',
    messagingSenderId: '594925660223',
    projectId: 'chatapp-ccd52',
    storageBucket: 'chatapp-ccd52.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSDb_q7ZIsBXc8tQVDc2x2KgCdhDRS8ws',
    appId: '1:594925660223:ios:760af08d8d4e176683b08a',
    messagingSenderId: '594925660223',
    projectId: 'chatapp-ccd52',
    storageBucket: 'chatapp-ccd52.appspot.com',
    iosBundleId: 'com.example.chatApplication.RunnerTests',
  );
}
